name: 创建新版本

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号（例如：1.0.0）'
        required: true
      is_prerelease:
        description: '是否为预发布版本'
        required: true
        default: false
        type: boolean

jobs:
  create-release:
    name: 创建版本
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 配置Git身份
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 更新版本号
        run: |
          VERSION=${{ github.event.inputs.version }}
          
          # 更新pubspec.yaml中的版本号
          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml
          
          # 更新版本更新日志
          echo "## $VERSION ($(date +'%Y-%m-%d'))" > temp_changelog.md
          echo "" >> temp_changelog.md
          echo "请在此添加版本更新内容" >> temp_changelog.md
          echo "" >> temp_changelog.md
          cat CHANGELOG.md >> temp_changelog.md
          mv temp_changelog.md CHANGELOG.md
          
          git add pubspec.yaml CHANGELOG.md
          git commit -m "chore: 版本更新至 $VERSION"

      - name: 创建标签和推送
        run: |
          VERSION=${{ github.event.inputs.version }}
          git tag -a "v$VERSION" -m "版本 $VERSION"
          git push origin "v$VERSION"
          git push

      - name: 创建GitHub发布版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: 索克生活 v${{ github.event.inputs.version }}
          draft: true
          prerelease: ${{ github.event.inputs.is_prerelease }}
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }} 